### ISSUE TITLE
[Remediation] florence-hartshorn preflight check

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/oregondigital#1473]
collection_id: florence-hartshorn

### Known Issues
- [x] Bad dates (Sarah)
- [x] Bad preds (Linda)

**Comment by lsat12357** [comment]
er, this is passing preflight, although I have no memory of working on it.
The only bad predicate reported was dc/terms/creator. Since there is no discussion here, hard to know if you approved the addition of the creator value.  The pids for which this change would have been made are on the bad_preds list in uo_pkg3( looks like there's 18 of them.

**Comment by sseymore** [comment]
The creators look good to me. Thanks!

**Comment by sseymore** [comment]
ready for preflight rerun

**Comment by lsat12357** [comment]
passing preflight
