### ISSUE TITLE
Evaluate options for replacing ubio.org URIs

### ISSUE THREAD

**Issue by wickr** [OregonDigital/oregondigital#1553]
ubio.org has been down for a significant time now, and a few years ago also had a long outage.
We've had some early discussions about how to replace existing ubio URIs but it's been hard to gauge without an export.

Scientific names dump CSV, as of 2022-05-31: 
https://docs.google.com/spreadsheets/d/1GcKHfyHd6FE9K0UUa8LB3leYXYhZDPfFZyXs_cErhvE/edit#gid=0

20,995 records with a URI in scientific names fields
22,306 ubio.org URIs total
??? unique ubio.org URIs
 
One of ubio.org's strengths was having entities for common names with separate IDs. ITIS often has common names associated with species entries but not with a separate ID. Another was having wide coverage since it aggregated data from multiple sources.

Possibilities:
- check ITIS for more matches
- check wikidata
- create terms in appropriate ONS vocab
- search for another linked data or API source

**Comment by carakey** [comment]
Spreadsheet magic says there are 1,558 unique ubio.org URIs. 
Of these, 36 unique URIs do not have an associated label - the label column in the spreadsheet repeated the URI.

List of unique URIs + labels + field in separate worksheet in same Google sheet linked above.

**Comment by carakey** [comment]
**Update**: I've done automatic reconciliation for all the ubio terms in both exports (scientific, lcsubject) against ITIS and Wikidata, and also against LCSH for those in lcsubject. Terms that couldn't be resolved automatically are split out as separate worksheets by primary set, at https://docs.google.com/spreadsheets/d/1GcKHfyHd6FE9K0UUa8LB3leYXYhZDPfFZyXs_cErhvE/edit#gid=1638387134:

- [ ] uo_oimb (150)
- [ ] osu_finley-bohlman (127)
- [ ] osu_osu-scarc (4)
- [ ] osu_lichens-pnw (5)
- [ ] osu_ken-gray (98)

Notes:

- Sheets are ordered by field; may want to pay special attention to lc subject and common names, decision criteria are likely to be different in those fields
- For lc subjects, I've searched LC + ITIS for all scientific name terms and LC + Wikidata for all common name terms; hits are included in the sheets, but I didn't make a determination on which should be used as the replacement. I did not find any conclusive results for one lcsubject term in OIMB.
- Many terms did have hits in Wikidata but not exact matches; worth checking before making new ONS terms.
- There are a couple dozen ubio URIs without labels, so there wasn't anything to automatically reconcile against. Hopefully we can figure these out by looking at individual items.

**Comment by carakey** [comment]
Reconciliation procedure (OSU), for the record:

- The majority of Ubio terms were able to be replaced automatically with exact label matches from ITIS, Wikidata, or LCSH as above, using OpenRefine and Google Sheets. 
- For all scientific name field replacements except common name, an ITIS URI was used if found, then Wikidata URI if found *and* if its label used the scientific name rather than the common name; if neither was available then we created a new Opaque Namespace term. 
- For common name, we decided to allow LCSH URIs (see #1561 and OregonDigital/OD2#2360). ITIS does not provide a common name entity; if a Wikidata label used the common name rather than the scientific name, then a Wikidata URI was preferred, then LCSH, then Opaque Namespace.
- For lcsubject, we decided to use an available LCSH URI that matches the concept even if the label would change to a scientific instead of common name or vice versa. For lcsubject replacements, LCSH URIs were preferred, then Wikidata. OSU did not need to make any new Opaque Namespace URIs for lcsubject terms. 
- GBIF was used as a main reference during reconciliation and SameAs links were included for GBIF in new ONS records. We could consider adding GBIF as a vocabulary source down the road. 
- In the reconciliation work, there were a number of organisms where a matching species URI couldn’t be found because the species has been reassigned into a different genus. I added an updated genus URI for these in the replacement list, including where the genus hadn’t been caught as an invalid/ubio term. This extended to updating the family as well for 2 items.

**Comment by carakey** [comment]
Following up on the previous comment, final bullet: For OSU items where the scientific name had changed, I added (1) an originalNameUsage with the existing name (author if known); (2) an acceptedNameUsage with the replacement name (author, date) ; (3) a scientificNameAuthorship with the replacement name author.

**Comment by carakey** [comment]
OSU batches ready for processing:

* 77 opaque namespace URIs [sheet](https://docs.google.com/spreadsheets/d/1GcKHfyHd6FE9K0UUa8LB3leYXYhZDPfFZyXs_cErhvE/edit#gid=708376963)
* 11,544 replacement RDF statements [sheet](https://docs.google.com/spreadsheets/d/1GcKHfyHd6FE9K0UUa8LB3leYXYhZDPfFZyXs_cErhvE/edit#gid=1040501103)
* 475 added RDF statements [sheet](https://docs.google.com/spreadsheets/d/1GcKHfyHd6FE9K0UUa8LB3leYXYhZDPfFZyXs_cErhvE/edit#gid=182049619)

As long as I'm reporting numbers, all together (OSU + UO) we had 1,630 unique Ubio URIs, found in 6 fields (phylum, family, genus, species, common name, lcsubject), of which 1,200 were able to be resolved automatically to exact matches.

**Comment by sseymore** [comment]
UO OIMB reconciliation is done. Replacement URIs are in the reconciling sheet, and opns URIS to create are in ons_batch_UO sheet. About 70 to create. Some have no replacements, so those will need to be deleted.

**Comment by wickr** [comment]
All known work on this has been completed. New terms were created in ONS. Batch replacements for UO and OSU are done, as well as some additional fields for some OSU records. Checked by searching for ubio.org URIs in all scientific name solr fields.
