### ISSUE TITLE
language

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/oregondigital#1566]
On OD1, there are assets that use a loc language uri that will not work on OD2

48 assets that use
http://id.loc.gov/vocabulary/iso639-2/fre
23 assets that use
http://id.loc.gov/vocabulary/iso639-2/ger
Is it ok for me to remediate all of these to /fra and /deu, respectively? (i.e. to match what is in the authorities file on OD2)

Additionally there are languages are not yet on the OD2 authorities list, making a separate ticket for that
http://id.loc.gov/vocabulary/iso639-2/hin
http://id.loc.gov/vocabulary/iso639-2/swa
https://github.com/OregonDigital/OD2/issues/2398

**Comment by lharka** [comment]
Linda asked me about this today and I am answering on behalf of Sarah Beth (Sarah Beth and/or Julia please feel free to call me out if I'm incorrect on this!). 

My thoughts:
Giving Linda the green light to go ahead and change language uris on the OD1 assets so that they match what is accepted by OD2. 

As a test, I tried searching for the language term like student catalogers normally do for collections and the OD2 versions (/fra and /deu) are the URIs that come up. It seems like /fre and /ger are just outdated or incorrect URIs that need to be changed anyway.

**Comment by lsat12357** [comment]
this is done.
