### ISSUE TITLE
Some predicates still not working correctly

### ISSUE THREAD

**Issue by mickeroo** [OregonDigital/oregondigital#769]
From the Hydra meeting on 1/23/15:
_Happens in both the form and view._
- Julia is working on the list of broken predicates
- Some show up in both the form inputs and the raw statements list (Creator is an example)
- _If the creators are showing up in raw statements then they are probably still DCE.creator vs. DCT_

**Comment by jsimic** [comment]
African Political Ephemera and Realia: label, type, name (geonames), prefLabel, longitude, latitude, countryCode, creator, contributor, earliestDate, latestDate, coverage, measurements, inscription, license, rights, set, full

Historic Sheet Music: label, type, creator, firstLineChorus, physicalExtent, locationCopyShelfLocator, license, rights, full

National Japanese American Student Relocation Council: creator, license

Oregon Daily Emerald Archives: 0

UO Veterans: militaryServiceLocation

Texts and Data: creator, rightsHolder, format

Mongolian Altai Inventory: note, label

Oregon Percent for Art: (in progress) creator, streetAddress, label, note, biographicalInformation.en

Picturing the Cayuse: identifier, alternative, subject, hasFormat, resolution, note, height, width, colorSpace

UO Office of the President: license, fileSize.en, creator, contributor

Northwest Folklife: label, collectors, contributors, note, culture

Western Waters Digital Library: license, filrSize.en, width, height, colorSpace, resolution, formOfWork

Oregon Latino Heritage: license

Building Oregon: creator, label, license, note

OIMB Slides: (in progress) 

UO Archives Photos: people, format

Artists' Books: (in progress)

Dissociation and Trauma Archives: (in progress) creator, note

Florence M Hartshorn: creator

Angelus Studio: colorSpace, resolution

Clarence L. Andrews: 0

Charles W. Furlong: 0

Dan Powell: (in progress) creator, colorSpace

Electric Studio/O.G. Allen: 0

Gertrude Bass Warner: colorSpace

Grayson Mathews: creator

James Cloutier: creator

John Bauguess: creator

Lee D. Drake: earliestDate, latestDate

Lee Moorhouse: creator, colorSpace, resolution

Roy C. Andrews: (in progress)

Randall V. Mills: creator

Walter S. Bowman: 0

Opal Whiteley: 0

Mayo Methot Bogart: creator, colorSpace, resolution

Frazier Augustus Boutelle: earliestDate, latestDate

Lesbian Intentional Communities: creator, license, people

Doris Ulmann: people

Manuscripts and Rare Books: (in progress)

UO Stock Photos: (in progress) creator, note, colourContent, license

Lowenstam: (in progress)

Archivision: (in progress)

Art & Architecture Images: (in progress)

Art & Architecture Images - Licensed: (in progress)

Jordan Schnitzer Museum of Art: (in progress)

Petrarch: 0

**Comment by srabun** [comment]
@kestlund @jsimic Is this still a blocker? I think it's unclear what else needs to be done...

**Comment by kestlund** [comment]
Yes, but @jsimic, and I can figure it out.

**Comment by sseymore** [comment]
Building Oregon:

After batch ingesting another 305 items, I'm seeing raw statements again for rightsHolder, stylePeriod, workType, streetAddress, and creator:

http://oregondigital.org/resource/oregondigital:df673902t http://purl.org/dc/terms/creator http://opaquenamespace.org/ns/creator/JTTedFrancis .
http://oregondigital.org/resource/oregondigital:df673902t http://www.loc.gov/mads/rdf/v1#streetAddress "3110 Portland Road, Newburg, OR 97132" .
http://oregondigital.org/resource/oregondigital:df673902t http://opaquenamespace.org/ns/vra/workType http://vocab.getty.edu/aat/300007140 .
http://oregondigital.org/resource/oregondigital:df673902t http://opaquenamespace.org/ns/vra/stylePeriod http://vocab.getty.edu/aat/300121793 .
http://oregondigital.org/resource/oregondigital:df673902t http://opaquenamespace.org/ns/vra/stylePeriod http://vocab.getty.edu/aat/300265600 .
http://oregondigital.org/resource/oregondigital:df673902t http://opaquenamespace.org/ns/rightsHolder http://id.loc.gov/authorities/names/no89008456 .

Also not in the n-triples.

for http://oregondigital.library.oregonstate.edu/ingest/oregondigital:df673902t

**Comment by lsat12357** [comment]
ok I see the problem with rightsHolder; in app/models/datastream/oregon_rdf.rb it is
:predicate => RDF::URI('http://opaquenamespace.org/rights/rightsHolder')
but in the json it is http://opaquenamespace.org/ns/rightsHolder
and that's what I've been using
