### ISSUE TITLE
question about 'citation' predicate

### ISSUE THREAD

**Issue by jcoyne** [OregonDigital/oregondigital#801]
Currently you are using: RDF::SCHEMA.citation which has the comment:
> A citation or reference to another creative work, such as another publication, web page, scholarly article, etc.

That sounds like "another work that cites this work." 

Why didn't you choose http://www.rdaregistry.info/Elements/u/#preferredCitation.en instead?

> Relates a resource to a citation for a resource in the form preferred by a creator, publisher, custodian, indexing or abstracting service, etc.

**Comment by kestlund** [comment]
I believe it was because we couldn't confirm that all of the "citations" were actually the preferredcitation of the work vs. another citation.  For instance, the Building Oregon collection cites a historic preservation manual not the preferred citation for the image.  @jsimic can explain in more detail.

**Comment by jcoyne** [comment]
:ok_hand: that sounds like you're using the correct predicate for the right reasons.  I just have different requirements than you.

**Comment by jsimic** [comment]
Yep, basically inconsistency.
