### ISSUE TITLE
Corazon de Dixie derivative videos are truncated

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/oregondigital#886]
Both videos have significant time missing from the end.
http://oregondigital.library.oregonstate.edu/sets/corazon-de-dixie/oregondigital:df70hn10s and http://oregondigital.library.oregonstate.edu/sets/corazon-de-dixie/oregondigital:fx71bc60m

**Comment by lsat12357** [comment]
I put them back in the derivative queue, the replacements still have the problem. Other details: the thumbnails are missing and the time bar controller does not allow you to move it; it shoots to the end of the bar as soon as play starts.

**Comment by lsat12357** [comment]
I forwarded the links to Duncan who responded:
Our web player is offering up the option of both a webm file and a mp4 file. The mp4 file 404s. Given that IE and Safari don’t support webm, this seems like a significant issue. If we’re going to have one format work, we really need the mp4 to work, since that’s actually compatible across all browsers.

I also note that our webm file doesn’t actually validate, i.e.:

dbarth$ mkvalidator --details oregondigital-fx71bc60m.webm 
ERR201: Invalid 'SegmentUID' for profile 'webm' in Info at 278
WRN801: The segment has no SeekHead section                   
WRN800: The segment has Clusters but no Cues section (bad for seeking)
.       file created with Lavf56.19.100 / Lavf56.19.100

This could be because the encode process didn’t finish. Also, looking at the resolution of the output file, theres no way this should take a day to create. On any reasonable system, I’d expect the transcode to take well under an hour. I think the next step is to take a closer look at what we’re actually doing to transcode the video; because I suspect we’re not doing it right.

**Comment by wickr** [comment]
Now that WebM files are disabled and only Mp4 video files are showing, these videos seem to be working correctly. The time of video content matches what's listed in Duration.

@lsat12357  if there are more that need fixing, you can add them to the Derivatives queue again and they should work this time.
